### ISSUE TITLE
[BUG] Regression finding coverage files to report in v10.1.0

### ISSUE THREAD

**Issue by justinvp** [codecov/codecov-cli#651]
**Describe the bug**

We upload coverage from a GitHub Actions workflow:

```yaml
      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        with:
          directory: coverage/
          files: "*,!.gitkeep"
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
```

We haven't made any configuration changes on our end, but we started seeing a significant drop in coverage in Codecov which coincided with the v10.1.0 release of the Codecov CLI.

Looking at the CI logs, when v10.0.1 of the Codecov CLI is used, it found [79 coverage files to report](https://github.com/pulumi/pulumi/actions/runs/13401482365/job/37434776513#step:6:87). With v10.1.0, it only finds [4 coverage files to report](https://github.com/pulumi/pulumi/actions/runs/13419253120/job/37490086100#step:6:214).

**Expected behavior**
To continue finding the same amount of coverage files to report

**Regression**
Yes. The last successful run that found all 79 files was Feb 18, 2025 at 3:27 PM PST. The next run that found only 4 files was at Feb 19, 2025 at 10:43 AM PST.

**Product Area**
coverage

**Versions**
 - OS: ubuntu@v22
 - Git Host: GitHub
 - CI/CD: GitHub Actions
 - Uploader: codecov-action@v4

**Commit and CI link**
Provide the commit SHA and CI link. If applicable, provide the entire Codecov output from CI.

_Example of success: 79 files found, using v10.0.1_:
- Commit: https://github.com/pulumi/pulumi/commit/feb243a15401049db5d66d88abc9c72d597797bc
- CI: https://github.com/pulumi/pulumi/actions/runs/13401482365/job/37434776513#step:6:1
- Logs: [logs-success.txt](https://github.com/user-attachments/files/18984344/logs-success.txt)

_Next commit that fails: only 4 files found, using v10.1.0_:
- Commit: https://github.com/pulumi/pulumi/commit/8c3c24e3bd891ba7a2c0d34d2b29fe4a26f51713
- CI: https://github.com/pulumi/pulumi/actions/runs/13419253120/job/37490086100#step:6:1
- Logs: [logs-failure.txt](https://github.com/user-attachments/files/18984347/logs-failure.txt)

**Additional context**
