### ISSUE TITLE
[BUG] latest (11.0.2) release does not work in CircleCI Orb 4.1.0 ("dlopen: Error relocating /tmp/...: pwritev2: symbol not found")

### ISSUE THREAD

**Issue by curtisfennergivery** [codecov/codecov-cli#689]
**Describe the bug**

We use [`codecov/codecov@4.1.0`](https://circleci.com/developer/orbs/orb/codecov/codecov?version=4.1.0) in our CircleCI job.

Starting sometime today, our CircleCI builds starting failing on the `codecov/upload` step. The error message looks like this:

```
./"codecov"  create-commit -t <redacted>
[PYI-1606:ERROR] Failed to load Python shared library '/tmp/_MEIdFielF/libpython3.12.so.1.0': dlopen: Error relocating /tmp/_MEIdFielF/libpython3.12.so.1.0: pwritev2: symbol not found

Exited with code exit status 255
```

**To Reproduce**
* Use the `codecov/codecov@4.1.0` CircleCI orb

```yaml
version: 2.1
orbs:
  codecov: codecov/codecov@5.4.3

jobs:
  tests:
    executor: with_core_dependencies
    steps:
      - checkout
      - run: sbt coverage test
      - run: sbt coverageAggregate
      - run: mkdir -p ~/.gnupg
      - codecov/upload:
          flags: "unit"

workflows:
  build_and_test:
    jobs:
      - tests
```

**Expected behavior**
Our builds continue working as they always have.

**Regression**
Builds fail because `codecov/upload` downloaded the `latest` (currently `v11.0.02`) version of the `codecov` CLI which no longer seems to work

**Product Area**
codecov CLI & CircleCI Orb

**Versions**
 - OS: ...
 - Git Host: GitHub
 - CI/CD: CircleCI
 - Uploader: CircleCI Orb [`codecov/codecov@4.1.0`](https://circleci.com/developer/orbs/orb/codecov/codecov?version=4.1.0) 

**Commit and CI link**
Provide the commit SHA and CI link. If applicable, provide the entire Codecov output from CI.

**Additional context**

To work around this, I am upgrading our CircleCI Orb from 4.1.0 to 5.4.3.

But backwards incompatible releases causing production disruption is **not** how release processes should work.

Either

* There should be a clear communication process of the end-of-life of an unsupported CircleCI Orb version
* The CircleCI orb should not (in its default configuration) use `/latest/` if that is not guaranteed to be compatible in the lifetime of the Orb
* The `/latest/` version should always remain compatible with (supported) CircleCI orb versions

I couldn't find any documentation on the support lifecycle for any Codecov tools... But I also found no evidence that version 4 should be unsupported. The changelog seems to be abandoned for 1+ year (https://docs.codecov.com/changelog) and the "GitHub release" link in the [actual codecov CLI artifact](https://cli.codecov.io/alpine/v11.0.2) which goes to https://cli.codecov.io/alpine/v11.0.2 and does not have any helpful information on migration
